spring:
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: org.postgresql.Driver
    username: brendan
    password: 123456
    url: 'jdbc:postgresql://localhost:5432/productms'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://liquorstore.us.auth0.com/'
  web:
    resources:
      add-mappings: false

management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'info, health'
      path-mapping:
        health: 'healthcheck'
      base-path: '/'

info:
  build:
    version": '1.0.0'
    artifact: 'product-ms'
    name: 'Product Microservice'
    time: ${maven.build.timestamp}

server:
  error:
    whitelabel:
      enabled: false

auth0:
  audience: 'https://product-ms.com'